### ISSUE TITLE
JS Errors in Console

### ISSUE THREAD

**Issue by mikebronner** [orthes/medium-editor-insert-plugin#331] opened 2016-06-12 19:51 UTC
I'm getting the following JS errors in the browser console on mouse-over (first error) and mouse-out (second error) on any of the insert-plugin icons. Further, not sure if this is related or not, the buttons are not styled the same as the main medium-editor plugin (they are blue, seem to be styled as links) instead of the theme color chosen by the medium-editor theme.

![screen shot 2016-06-12 at 12 47 29 pm](https://cloud.githubusercontent.com/assets/1791050/15993474/4f6f402e-309c-11e6-9429-4307f3dc3c2f.png)

**Comment by brunjick** [comment] 2016-06-12 20:54
Same here...

**Comment by smalluban** [comment] 2016-06-14 09:41
I checked medium-editor releases and problem starts with `^5.19.1` version. I think it is related with `Add feature for toggling anchor preview for empty or # links` feature added in this version. It should be fixed in `5.20` but the problem still exists.

**Comment by nmielnik** [comment] 2016-07-08 00:42
@mikebronner @brunjick @smalluban @jcalfee @lauranjansen can you try using the latest version of medium-editor, and when instantiating it pass the `anchorPreview.showOnEmptyLink` option as `false`?

```js
var editor = new MediumEditor('.editor', {
    anchorPreview: {
        showOnEmptyLink: false
    }
});
```

I believe this will be a workaround to let you upgrade to the latest version.  The one side-effect will be that if you have any anchors in your editors that have an empty `href` or `href="#"`, the anchor-preview won't display when you hover over them.

I think the root cause of this is that the + button is an actual link within the editor.  Before, since the anchor-preview was always disabled when hovering links with no `href`, the anchor-preview ignored this + button.  Now that we allow anchor-preview to display for all links, it's now treat the button as if it's a regular link.

Some potential long term fixes for this:
1. Make the + button not be a link
2. Make the + button not be within the actual editor
3. Add a feature to medium-editor to 'blacklist' certain links from being monitored by anchor-preview (maybe a class, data-attribute, or something).  Then, in the plugin, adding this attribute to the + button.

In the future fellas, don't hesitate to open an issue in medium-editor, we might have been able to help you out sooner!

**Comment by jcalfee** [comment] 2016-07-08 01:01
Error still happens with `showOnEmptyLinks: false`.  I think the errors are not too bad though, they don't seem to cause a problem.

**Comment by lauranjansen** [comment] 2016-07-08 13:06
Workaround seems to have solved it for me, thanks!

**Comment by orthes** [comment] 2016-07-20 15:53
I'm fixing this error in #355

**Closed by orthes** 2016-07-20 15:53 UTC
Labels: bug
