### ISSUE TITLE
Mouse movement triggers errors

### ISSUE THREAD

**Issue by jcalfee** [orthes/medium-editor-insert-plugin#345] opened 2016-07-05 19:00 UTC
As the mouse pointer moves over the + icon:

![image](https://cloud.githubusercontent.com/assets/204121/16596108/01cfa0f6-42b8-11e6-8eb1-209ece9b5635.png)

The mouse move events trigger these errors:

![image](https://cloud.githubusercontent.com/assets/204121/16596133/2593cbb6-42b8-11e6-8b98-aea2839c83ba.png)

```
├─┬ medium-editor-insert-plugin@2.3.2
│ └── medium-editor@5.21.0 
```
The first error is `medium-editor.js:4042 Uncaught TypeError: Cannot read property 'value' of undefined`

That points to the 2nd if statement 1st line, attributes.href is null:
```js
        showPreview: function (anchorEl) {
            if (this.anchorPreview.classList.contains('medium-editor-anchor-preview-active') ||
                    anchorEl.getAttribute('data-disable-preview')) {
                return true;
            }

            if (this.previewValueSelector) {
                this.anchorPreview.querySelector(this.previewValueSelector).textContent = anchorEl.attributes.href.value;
                this.anchorPreview.querySelector(this.previewValueSelector).href = anchorEl.attributes.href.value;
            }
...
```

**Comment by jcalfee** [comment] 2016-07-06 14:15
Is it just me or everyone?  So I know to investigate more .. thank you

**Comment by lauranjansen** [comment] 2016-07-06 21:43
I'm seeing this as well after trying to upgrade the plugin to the most recent version, same errors, same lines in the code.

**Comment by lauranjansen** [comment] 2016-07-06 22:24
Downgrading Medium Editor to 5.18.0 seems to have solved this error, not sure what's going on...

**Comment by lauranjansen** [comment] 2016-07-07 15:11
Duplicate of https://github.com/orthes/medium-editor-insert-plugin/issues/331

**Comment by nmielnik** [comment] 2016-07-08 00:43
@jcalfee @lauranjansen see my recommended workaround in #331.  Could you close this issue since it's a duplicate?

**Closed** 2016-07-08 00:56 UTC
