### ISSUE TITLE
Cannot embed Tweets

### ISSUE THREAD

**Issue by tvsloot** [orthes/medium-editor-insert-plugin#229] opened 2015-10-04 19:07 UTC
Plugin works great for Facebook, Instagram, YouTube, and Vimeo, but I cannot get Tweets to embed. When I add the url, the tweet appears in the editor, but when I save my changes, the Twitter iframe html has an empty head and body. Am I missing something here, or is anyone else having the same issue?

**Comment by j0k3r** [comment] 2015-10-05 05:47
Could you give us a jsfiddle so we can reproduce what you described? Thanks

**Comment by tvsloot** [comment] 2015-10-05 13:44
I can include a jsfiddle of the end result: https://jsfiddle.net/gjaoLjes/

I am using this plugin for my Laravel CMS application. The Tweet appears when entered into the form, but when I save to the database, this is what happens.

**Comment by j0k3r** [comment] 2015-10-05 14:05
Maybe you need to manually call `twttr.widgets.load()` to re-enable the tweet.

**Comment by orthes** [comment] 2015-10-06 05:00
Yes, I know about this problem. That's why the recommended approach is to use ```oembedProxy``` and let an oEmbed provider handle embed codes.

**Comment by romainmougel** [comment] 2015-10-22 18:52
I had the same problem, I solved with this script. It must be added on the editing page and on the rendering page to work. It basically get the tweet ID, remove the old one and add a new one at the same place :

                  $.getScript('//platform.twitter.com/widgets.js', function(){ 
		    	var k = 0;
		    	var tweet = document.getElementById('twitter-widget-'+k);
		    	var tweetTest = tweet ? true : false;
		    	var tweetParent, tweetID;
		    	while(tweetTest) {
		    		tweetParent = tweet.parentNode;
		    		tweetID = tweet.dataset.tweetId;
		    		$(tweet).remove();
			        twttr.widgets.createTweet(
					  tweetID,
					  tweetParent
				);
				k++;
				tweet = document.getElementById('twitter-widget-'+k);
		    		tweetTest = tweet ? true : false;
			    }
		    });

I know this is not really clean code (mixing jQuery & javascript) but it works for me.
Note that when you add an embed tweet it also adds a script tag that I remove server-side directly.

**Comment by vladman** [comment] 2015-11-18 01:19
I also had this problem:

      $("iframe[id^='twitter-widget-']").each(function() {
          twttr.widgets.createTweet($(this).data('tweet-id'), this.parentNode);
          $(this).remove();
      });

Most likely you will need to clean the parent folder from the other stuff. At least from &lt;script async="" src="//platform.twitter.com/widgets.js" charset="utf-8"&gt;&lt;/script&gt;
It's a good idea to wrap the original embed code with div and use

      $(this).parent().empty();

**Comment by orthes** [comment] 2016-02-27 09:14
Fixed in #277

**Closed by orthes** 2016-02-27 09:14 UTC
Labels: bug
